<?xml version="1.0" encoding="utf-8"?><Database Name="C3Comparison" Class="SqlComparisonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=C3Comparison;Integrated Security=True" SettingsObjectName="Atmosphere.Core.Properties.Settings" SettingsPropertyName="MockComparisonConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ComparisonDataItem" Member="ComparisonDataItems">
    <Type Name="ComparisonDataItem">
      <Column Name="ComparisonDataItemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemGroupTypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPatients" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ComparisonDataItem_ComparisonDataItemMeasure" Member="ComparisonDataItemMeasures" ThisKey="ComparisonDataItemId" OtherKey="ComparisonDataItemId" Type="ComparisonDataItemMeasure" />
      <Association Name="GroupSubscriber_ComparisonDataItem" Member="GroupSubscriber" ThisKey="GroupId" OtherKey="GroupSubscriberId" Type="GroupSubscriber" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubscriberPatient" Member="SubscriberPatients">
    <Type Name="SubscriberPatient">
      <Column Name="SubscriberPatientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Patient_SubscriberPatient" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" />
      <Association Name="Subscriber_SubscriberPatient" Member="Subscriber" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="Subscriber" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ComparisonDataItemMeasure" Member="ComparisonDataItemMeasures">
    <Type Name="ComparisonDataItemMeasure">
      <Column Name="ComparisonDataItemMeasureId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ComparisonDataItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeasureId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Numerator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Denominator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Exclusions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ComparisonDataItem_ComparisonDataItemMeasure" Member="ComparisonDataItem" ThisKey="ComparisonDataItemId" OtherKey="ComparisonDataItemId" Type="ComparisonDataItem" IsForeignKey="true" />
      <Association Name="Measure_ComparisonDataItemMeasure" Member="Measure" ThisKey="MeasureId" OtherKey="MeasureId" Type="Measure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Condition" Member="Conditions">
    <Type Name="Condition">
      <Column Name="ConditionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ConditionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Condition_ConditionPopulation" Member="ConditionPopulations" ThisKey="ConditionId" OtherKey="ConditionId" Type="ConditionPopulation" />
      <Association Name="Condition_ProgramCondition" Member="ProgramConditions" ThisKey="ConditionId" OtherKey="ConditionId" Type="ProgramCondition" />
    </Type>
  </Table>
  <Table Name="dbo.ConditionPopulation" Member="ConditionPopulations">
    <Type Name="ConditionPopulation">
      <Column Name="ConditionPopulationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ConditionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PopulationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ConditionPopulation_Measure" Member="Measures" ThisKey="ConditionPopulationId" OtherKey="ConditionPopulationId" Type="Measure" />
      <Association Name="Condition_ConditionPopulation" Member="Condition" ThisKey="ConditionId" OtherKey="ConditionId" Type="Condition" IsForeignKey="true" />
      <Association Name="Population_ConditionPopulation" Member="Population" ThisKey="PopulationId" OtherKey="PopulationId" Type="Population" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contract" Member="Contracts">
    <Type Name="Contract">
      <Column Name="ContractId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContractName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Contract_ContractGroup" Member="ContractGroups" ThisKey="ContractId" OtherKey="ContractId" Type="ContractGroup" />
    </Type>
  </Table>
  <Table Name="dbo.ContractGroup" Member="ContractGroups">
    <Type Name="ContractGroup">
      <Column Name="ContractGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ContractGroup_ContractGroupProgram" Member="ContractGroupPrograms" ThisKey="ContractGroupId" OtherKey="ContractGroupId" Type="ContractGroupProgram" />
      <Association Name="Contract_ContractGroup" Member="Contract" ThisKey="ContractId" OtherKey="ContractId" Type="Contract" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractGroupProgram" Member="ContractGroupPrograms">
    <Type Name="ContractGroupProgram">
      <Column Name="ContractGroupProgramId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContractGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ContractGroup_ContractGroupProgram" Member="ContractGroup" ThisKey="ContractGroupId" OtherKey="ContractGroupId" Type="ContractGroup" IsForeignKey="true" />
      <Association Name="Program_ContractGroupProgram" Member="Program" ThisKey="ProgramId" OtherKey="ProgramId" Type="Program" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Group_GroupSubscriber" Member="GroupSubscribers" ThisKey="GroupId" OtherKey="GroupId" Type="GroupSubscriber" />
    </Type>
  </Table>
  <Table Name="dbo.GroupSubscriber" Member="GroupSubscribers">
    <Type Name="GroupSubscriber">
      <Column Name="GroupSubscriberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GroupSubscriber_ComparisonDataItem" Member="ComparisonDataItems" ThisKey="GroupSubscriberId" OtherKey="GroupId" Type="ComparisonDataItem" />
      <Association Name="Group_GroupSubscriber" Member="Group" ThisKey="GroupId" OtherKey="GroupId" Type="Group" IsForeignKey="true" />
      <Association Name="Subscriber_GroupSubscriber" Member="Subscriber" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="Subscriber" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Measure" Member="Measures">
    <Type Name="Measure">
      <Column Name="MeasureId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ConditionPopulationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeasureName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Measure_ComparisonDataItemMeasure" Member="ComparisonDataItemMeasures" ThisKey="MeasureId" OtherKey="MeasureId" Type="ComparisonDataItemMeasure" />
      <Association Name="ConditionPopulation_Measure" Member="ConditionPopulation" ThisKey="ConditionPopulationId" OtherKey="ConditionPopulationId" Type="ConditionPopulation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientPatientId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Patient_SubscriberPatient" Member="SubscriberPatients" ThisKey="PatientId" OtherKey="PatientId" Type="SubscriberPatient" />
    </Type>
  </Table>
  <Table Name="dbo.Population" Member="Populations">
    <Type Name="Population">
      <Column Name="PopulationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PopulationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Population_ConditionPopulation" Member="ConditionPopulations" ThisKey="PopulationId" OtherKey="PopulationId" Type="ConditionPopulation" />
    </Type>
  </Table>
  <Table Name="dbo.Program" Member="Programs">
    <Type Name="Program">
      <Column Name="ProgramId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Program_ContractGroupProgram" Member="ContractGroupPrograms" ThisKey="ProgramId" OtherKey="ProgramId" Type="ContractGroupProgram" />
      <Association Name="Program_ProgramCondition" Member="ProgramConditions" ThisKey="ProgramId" OtherKey="ProgramId" Type="ProgramCondition" />
    </Type>
  </Table>
  <Table Name="dbo.ProgramCondition" Member="ProgramConditions">
    <Type Name="ProgramCondition">
      <Column Name="ProgramConditionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConditionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Condition_ProgramCondition" Member="Condition" ThisKey="ConditionId" OtherKey="ConditionId" Type="Condition" IsForeignKey="true" />
      <Association Name="Program_ProgramCondition" Member="Program" ThisKey="ProgramId" OtherKey="ProgramId" Type="Program" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscriber" Member="Subscribers">
    <Type Name="Subscriber">
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubscriberName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Subscriber_SubscriberPatient" Member="SubscriberPatients" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="SubscriberPatient" />
      <Association Name="Subscriber_GroupSubscriber" Member="GroupSubscribers" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="GroupSubscriber" />
    </Type>
  </Table>
</Database>