//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace TestCommService.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CallResultsServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CallResultsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendOCQEResultsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CallResultsService() {
            this.Url = global::TestCommService.Properties.Settings.Default.TestCommService_localhost_CallResultsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendOCQEResultsCompletedEventHandler sendOCQEResultsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendOCQEResults", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public respObject_Array sendOCQEResults(reqObject_Array parameters) {
            object[] results = this.Invoke("sendOCQEResults", new object[] {
                        parameters});
            return ((respObject_Array)(results[0]));
        }
        
        /// <remarks/>
        public void sendOCQEResultsAsync(reqObject_Array parameters) {
            this.sendOCQEResultsAsync(parameters, null);
        }
        
        /// <remarks/>
        public void sendOCQEResultsAsync(reqObject_Array parameters, object userState) {
            if ((this.sendOCQEResultsOperationCompleted == null)) {
                this.sendOCQEResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendOCQEResultsOperationCompleted);
            }
            this.InvokeAsync("sendOCQEResults", new object[] {
                        parameters}, this.sendOCQEResultsOperationCompleted, userState);
        }
        
        private void OnsendOCQEResultsOperationCompleted(object arg) {
            if ((this.sendOCQEResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendOCQEResultsCompleted(this, new sendOCQEResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class reqObject_Array {
        
        private reqObject[] gfRequestField;
        
        /// <remarks/>
        public reqObject[] gfRequest {
            get {
                return this.gfRequestField;
            }
            set {
                this.gfRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class reqObject {
        
        private int sendIDField;
        
        private string contractIDField;
        
        private int facilityIDField;
        
        private System.Nullable<int> providerIDField;
        
        private int activityIDField;
        
        private System.Nullable<int> scheduleIDField;
        
        private int commEventIDField;
        
        private string callIDField;
        
        private System.DateTime callDistributorTimeOfCallField;
        
        private long callDurationField;
        
        private string resultCodeField;
        
        private string resultStatusField;
        
        private string hangupLocaleField;
        
        private bool recordingField;
        
        private string fileLocationField;
        
        private string fileNameField;
        
        private string languageResultsCodeField;
        
        private string transferPrimaryStatusCodeField;
        
        private string transferSecondaryStatusCodeField;
        
        private string transferDestinationField;
        
        private string commDialerIPField;
        
        private string commRecordingServerIPField;
        
        private string commApplicationURLField;
        
        private string commMediaServerIPField;
        
        private string commVXMLBrowserField;
        
        private System.Nullable<int> commChannelField;
        
        /// <remarks/>
        public int SendID {
            get {
                return this.sendIDField;
            }
            set {
                this.sendIDField = value;
            }
        }
        
        /// <remarks/>
        public string ContractID {
            get {
                return this.contractIDField;
            }
            set {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        public int FacilityID {
            get {
                return this.facilityIDField;
            }
            set {
                this.facilityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
        
        /// <remarks/>
        public int ActivityID {
            get {
                return this.activityIDField;
            }
            set {
                this.activityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ScheduleID {
            get {
                return this.scheduleIDField;
            }
            set {
                this.scheduleIDField = value;
            }
        }
        
        /// <remarks/>
        public int CommEventID {
            get {
                return this.commEventIDField;
            }
            set {
                this.commEventIDField = value;
            }
        }
        
        /// <remarks/>
        public string CallID {
            get {
                return this.callIDField;
            }
            set {
                this.callIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CallDistributorTimeOfCall {
            get {
                return this.callDistributorTimeOfCallField;
            }
            set {
                this.callDistributorTimeOfCallField = value;
            }
        }
        
        /// <remarks/>
        public long CallDuration {
            get {
                return this.callDurationField;
            }
            set {
                this.callDurationField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public string HangupLocale {
            get {
                return this.hangupLocaleField;
            }
            set {
                this.hangupLocaleField = value;
            }
        }
        
        /// <remarks/>
        public bool Recording {
            get {
                return this.recordingField;
            }
            set {
                this.recordingField = value;
            }
        }
        
        /// <remarks/>
        public string FileLocation {
            get {
                return this.fileLocationField;
            }
            set {
                this.fileLocationField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageResultsCode {
            get {
                return this.languageResultsCodeField;
            }
            set {
                this.languageResultsCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TransferPrimaryStatusCode {
            get {
                return this.transferPrimaryStatusCodeField;
            }
            set {
                this.transferPrimaryStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TransferSecondaryStatusCode {
            get {
                return this.transferSecondaryStatusCodeField;
            }
            set {
                this.transferSecondaryStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TransferDestination {
            get {
                return this.transferDestinationField;
            }
            set {
                this.transferDestinationField = value;
            }
        }
        
        /// <remarks/>
        public string CommDialerIP {
            get {
                return this.commDialerIPField;
            }
            set {
                this.commDialerIPField = value;
            }
        }
        
        /// <remarks/>
        public string CommRecordingServerIP {
            get {
                return this.commRecordingServerIPField;
            }
            set {
                this.commRecordingServerIPField = value;
            }
        }
        
        /// <remarks/>
        public string CommApplicationURL {
            get {
                return this.commApplicationURLField;
            }
            set {
                this.commApplicationURLField = value;
            }
        }
        
        /// <remarks/>
        public string CommMediaServerIP {
            get {
                return this.commMediaServerIPField;
            }
            set {
                this.commMediaServerIPField = value;
            }
        }
        
        /// <remarks/>
        public string CommVXMLBrowser {
            get {
                return this.commVXMLBrowserField;
            }
            set {
                this.commVXMLBrowserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CommChannel {
            get {
                return this.commChannelField;
            }
            set {
                this.commChannelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class respObject {
        
        private string callIDField;
        
        private string returnStatusField;
        
        private string returnStringField;
        
        /// <remarks/>
        public string CallID {
            get {
                return this.callIDField;
            }
            set {
                this.callIDField = value;
            }
        }
        
        /// <remarks/>
        public string returnStatus {
            get {
                return this.returnStatusField;
            }
            set {
                this.returnStatusField = value;
            }
        }
        
        /// <remarks/>
        public string returnString {
            get {
                return this.returnStringField;
            }
            set {
                this.returnStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class respObject_Array {
        
        private respObject[] gfResponseField;
        
        /// <remarks/>
        public respObject[] gfResponse {
            get {
                return this.gfResponseField;
            }
            set {
                this.gfResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sendOCQEResultsCompletedEventHandler(object sender, sendOCQEResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendOCQEResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendOCQEResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respObject_Array Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respObject_Array)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591