//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3GroupEntity
    {
        public int C3GroupEntityId { get; set; }
        public int C3GroupId { get; set; }
        public int EntityId { get; set; }
        public int C3GroupEntityTypeId { get; set; }
        public bool DeleteFlag { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual C3Group C3Group { get; set; }
        public virtual C3GroupEntityType C3GroupEntityType { get; set; }
    }
}
