//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3NotePatient
    {
        public int NoteId { get; set; }
        public string Note { get; set; }
        public int ActionID { get; set; }
        public int CategoryId { get; set; }
        public int PatientId { get; set; }
        public int CampaignId { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> DeletedStatus { get; set; }
        public string CampaignName { get; set; }
    }
}
