//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3ProblemList
    {
        public int ProblemListID { get; set; }
        public int PatientID { get; set; }
        public string ProblemExternalCode { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> ProblemTypeID { get; set; }
        public string ProblemTypeDescription { get; set; }
    }
}
