//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRegistryHdr
    {
        public int PatientRegistryHdrID { get; set; }
        public int PATIENTID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public Nullable<System.DateTime> PatientDOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> SUBSCRIBERID { get; set; }
        public Nullable<int> PrimaryCareFlag { get; set; }
        public Nullable<int> CalendarID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> OverrideProviderID { get; set; }
        public Nullable<int> OverrideFacilityID { get; set; }
        public Nullable<System.DateTime> FirstApptDate { get; set; }
        public Nullable<System.DateTime> LastApptDate { get; set; }
        public Nullable<System.DateTime> NextApptDate { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<System.DateTime> LastChronicApptDate { get; set; }
        public Nullable<System.DateTime> LastPreventativeApptDate { get; set; }
        public Nullable<int> DaysSinceFirstAppt { get; set; }
        public Nullable<int> DaysSinceLastAppt { get; set; }
        public Nullable<int> DaysSinceLastChronic { get; set; }
        public Nullable<int> DaysSinceLastPreventative { get; set; }
        public Nullable<int> DaysUntilNextAppt { get; set; }
        public Nullable<int> DaysFutureApptExclusion { get; set; }
        public string AreaCode { get; set; }
        public string PhoneNumberString { get; set; }
        public string EmailAddress { get; set; }
        public string StudyGroup { get; set; }
        public string StudyGroupStatus { get; set; }
        public string ExternalID { get; set; }
        public Nullable<System.DateTime> FirstRecallDate { get; set; }
        public Nullable<System.DateTime> LastRecallDate { get; set; }
        public Nullable<int> TotalAttemptCnt { get; set; }
        public Nullable<int> AccessCount { get; set; }
        public int ChronicFlag { get; set; }
        public int PreventativeFlag { get; set; }
        public int AncillaryFlag { get; set; }
        public int ManualFlag { get; set; }
        public int NC_Chronic { get; set; }
        public int NC_Preventative { get; set; }
        public int NC_Ancillary { get; set; }
        public int NC_Manual { get; set; }
        public int NC_Any { get; set; }
        public int InactiveFlag { get; set; }
        public int DataStatus { get; set; }
        public int DeleteFlag { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> AgeInMonths { get; set; }
    }
}
