//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberSolution
    {
        public int SUBSCRIBERSOLUTIONID { get; set; }
        public int SUBSCRIBERID { get; set; }
        public int SOLUTIONID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public decimal Price { get; set; }
        public decimal Qty { get; set; }
        public decimal IncludedTransactions { get; set; }
        public decimal TransactionFee { get; set; }
        public int BillType { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxPrice { get; set; }
        public int DeleteFlag { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> BillingEffectiveDate { get; set; }
    }
}
