CREATE VIEW [dbo].[vw_aspnet_MembershipUsers]
  AS SELECT [dbo].[Membership].[UserId],
            [dbo].[Membership].[PasswordFormat],
            [dbo].[Membership].[MobilePIN],
            [dbo].[Membership].[Email],
            [dbo].[Membership].[LoweredEmail],
            [dbo].[Membership].[PasswordQuestion],
            [dbo].[Membership].[PasswordAnswer],
            [dbo].[Membership].[IsApproved],
            [dbo].[Membership].[IsLockedOut],
            [dbo].[Membership].[CreateDate],
            [dbo].[Membership].[LastLoginDate],
            [dbo].[Membership].[LastPasswordChangedDate],
            [dbo].[Membership].[LastLockoutDate],
            [dbo].[Membership].[FailedPasswordAttemptCount],
            [dbo].[Membership].[FailedPasswordAttemptWindowStart],
            [dbo].[Membership].[FailedPasswordAnswerAttemptCount],
            [dbo].[Membership].[FailedPasswordAnswerAttemptWindowStart],
            [dbo].[Membership].[Comment],
            [dbo].[User].[ApplicationId],
            [dbo].[User].[UserName],
            [dbo].[User].[MobileAlias],
            [dbo].[User].[IsAnonymous],
            [dbo].[User].[LastActivityDate]
  FROM [dbo].[Membership] INNER JOIN [dbo].[User]
      ON [dbo].[Membership].[UserId] = [dbo].[User].[UserId]
