//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3GroupEntityType
    {
        public C3GroupEntityType()
        {
            this.C3GroupEntity = new HashSet<C3GroupEntity>();
        }
    
        public int C3GroupEntityTypeId { get; set; }
        public string Name { get; set; }
        public bool DeleteFlag { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<C3GroupEntity> C3GroupEntity { get; set; }
    }
}
