//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyData
    {
        public int KeyDataID { get; set; }
        public int OwnerID { get; set; }
        public string KeyData1 { get; set; }
        public string CategoryCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<byte> DeleteFlag { get; set; }
    
        public virtual ContactEntity ContactEntity { get; set; }
    }
}
