//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phytel.Engage.Integrations.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberEntity
    {
        public int SUBSCRIBERENTITYID { get; set; }
        public int SUBSCRIBERID { get; set; }
        public int FACILITYID { get; set; }
        public int CONTACTENTITYID { get; set; }
        public string EntityName { get; set; }
        public string CategoryCode { get; set; }
        public int PreferredFlag { get; set; }
        public int Enable_RC { get; set; }
        public int Enable_AR { get; set; }
        public int Enable_TA { get; set; }
        public int DeleteFlag { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string TIN { get; set; }
        public string NPI { get; set; }
        public int Enable_PS { get; set; }
    }
}
